export const SKILL_MODEL = 'SKILL_MODEL';
export const TEAM_MODEL = 'TEAM_MODEL';
export const HOLIDAY_MODEL = 'HOLIDAY_MODEL';
export const SICK_LEAVE_MODEL = 'SICK_LEAVE_MODEL';
export const WORKING_TIME_MODEL = 'WORKING_TIME_MODEL';

