export const SKILLS_REPOSITORY = Symbol.for('SKILLS_REPOSITORY');
export const PERMISSIONS_REPOSITORY = Symbol.for('PERMISSIONS_REPOSITORY');
export const ROLES_REPOSITORY = Symbol.for('ROLES_REPOSITORY');
